const MINUTE_MS = 60 * 1000;
export const GAME = {
  DELAY_MS: 50,
  BOARD_COLUMNS: 140,
  BOARD_ROWS: 70,
  DEAD: 0,
  ALIVE: 1,
  REPRODUCTION_POPULATION: 3,
  UNDER_POPULATION: 2,
  OVER_POPULATION: 3,
  LIFE_PROBABILITY: 0.44,
  LIVE_GAME_MS: MINUTE_MS
};