const MINUTE_MS = 60 * 1000;
export const GAME = {
  IS_ALIVE: 1,
  BOARD_COLUMNS: 140,
  BOARD_ROWS: 70,
  IS_DEAD: 0,
  DELAY_MS: 50,
  LIFE_PROBABILITY: 0.44,
  LIVE_GAME_MS: MINUTE_MS,
  OVER_POPULATION: 3,
  REPRODUCTION_POPULATION: 3,
  UNDER_POPULATION: 2
};
